---
- name: Testing andrewrothstein.kubectl
  hosts: all
  tasks:
    - name: Installing andrewrothstein.kubectl
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'kubectl version --client=true'
      ansible.builtin.command: /usr/local/bin/kubectl version --client=true
      changed_when: false
      register: kubectl_test_output
    - name: Output from 'kubectl version --client=true'
      ansible.builtin.debug:
        msg: '{{ kubectl_test_output.stdout }}'
