---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/kubectl version
    register: kubectl_test_output
  - debug:
      msg: '{{ kubectl_test_output.stdout }}'
