---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'

- name: create install directory {{ kubectl_install_dir }}...
  become: '{{ kubectl_privilege_escalate }}'
  become_user: root
  file:
    path: '{{ kubectl_install_dir }}'
    state: directory
    mode: '0755'

- name: downloading {{ kubectl_url }} to {{ kubectl_install_exe }}...
  become: '{{ kubectl_privilege_escalate }}'
  become_user: root
  get_url:
    url: '{{ kubectl_url }}'
    dest: '{{ kubectl_install_exe }}'
    checksum: '{{ kubectl_checksum }}'
    mode: '0755'

- name: linking {{ kubectl_install_link }} to {{ kubectl_install_exe }}...
  become: '{{ kubectl_privilege_escalate }}'
  become_user: root
  file:
    src: '{{ kubectl_install_exe }}'
    dest: '{{ kubectl_install_link }}'
    state: link

- when: kubectl_install_completions
  block:
    - name: create bash completions directory {{ kubectl_bash_completion_dir }}...
      become: '{{ kubectl_privilege_escalate }}'
      become_user: root
      file:
        path: '{{ kubectl_bash_completion_dir }}'
        state: directory
        mode: '0755'
    - name: getting kubectl bash completion...
      command: '{{ kubectl_install_link }} completion bash'
      register: kubectl_bash_completion
      changed_when: false
    - name: installing kubectl bash completion to {{ kubectl_bash_completion_file }}...
      become: '{{ kubectl_privilege_escalate }}'
      become_user: root
      copy:
        content: '{{ kubectl_bash_completion.stdout }}'
        dest: '{{ kubectl_bash_completion_file }}'
