---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'

- name: Create install directory {{ kubectl_install_dir }}...
  become: '{{ kubectl_privilege_escalate }}'
  become_user: root
  ansible.builtin.file:
    path: '{{ kubectl_install_dir }}'
    state: directory
    mode: '755'

- name: Downloading {{ kubectl_url }} to {{ kubectl_install_exe }}...
  become: '{{ kubectl_privilege_escalate }}'
  become_user: root
  ansible.builtin.get_url:
    url: '{{ kubectl_url }}'
    dest: '{{ kubectl_install_exe }}'
    checksum: '{{ kubectl_checksum }}'
    mode: '755'

- name: Linking {{ kubectl_install_link }} to {{ kubectl_install_exe }}...
  become: '{{ kubectl_privilege_escalate }}'
  become_user: root
  ansible.builtin.file:
    src: '{{ kubectl_install_exe }}'
    dest: '{{ kubectl_install_link }}'
    state: link
